# Build stage
FROM node:20-slim AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG VITE_BACKEND_URL
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

RUN npm run build

# Production stage
FROM jonasal/nginx-certbot:latest

# Copy built files
COPY --from=build /app/dist /usr/share/nginx/html

# Copy production nginx config
COPY user_conf.d/server.prod.conf /etc/nginx/user_conf.d/server.conf

EXPOSE 80 443