apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker/docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: icam-secret
                  key: API_KEY
            - name: DOCKER
              value: "true"
            - name: ES_URL
              value: https://es01:9200
            - name: INDEX
              valueFrom:
                configMapKeyRef:
                  name: icam-config
                  key: INDEX
            - name: CERT_PATH
              value: /usr/share/elasticsearch/config/certs/ca/ca.crt
          image: vikrampen/icam-backend:latest
          volumeMounts:
            - name: certs
              mountPath: /usr/share/elasticsearch/config/certs
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          name: backend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs
