apiVersion: v1
kind: Service
metadata:
  annotations:
    co.elastic.logs/module: elasticsearch
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: es01
  name: es01
spec:
  type: NodePort
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
      nodePort: 30920
  selector:
    io.kompose.service: es01
