apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    co.elastic.logs/module: elasticsearch
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: es01
  name: es01
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: es01
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        co.elastic.logs/module: elasticsearch
        kompose.cmd: kompose convert -f ../docker/docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: es01
    spec:
      containers:
        - env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icam-secret
                  key: ELASTIC_PASSWORD
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.name
              valueFrom:
                configMapKeyRef:
                  name: icam-config
                  key: CLUSTER_NAME
            - name: discovery.type
              value: single-node
            - name: node.name
              value: es01
            - name: xpack.license.self_generated.type
              valueFrom:
                configMapKeyRef:
                  name: icam-config
                  key: LICENSE
            - name: xpack.security.enabled
              value: "true"
            - name: xpack.security.http.ssl.certificate
              value: certs/es01/es01.crt
            - name: xpack.security.http.ssl.certificate_authorities
              value: certs/ca/ca.crt
            - name: xpack.security.http.ssl.enabled
              value: "true"
            - name: xpack.security.http.ssl.key
              value: certs/es01/es01.key
            - name: xpack.security.transport.ssl.certificate
              value: certs/es01/es01.crt
            - name: xpack.security.transport.ssl.certificate_authorities
              value: certs/ca/ca.crt
            - name: xpack.security.transport.ssl.enabled
              value: "true"
            - name: xpack.security.transport.ssl.key
              value: certs/es01/es01.key
            - name: xpack.security.transport.ssl.verification_mode
              value: certificate
          image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
          livenessProbe:
            httpGet:
              path: /
              port: 9200
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          name: es01
          ports:
            - containerPort: 9200
              protocol: TCP
          resources:
            limits:
              memory: "2147483648"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/config/certs
              name: certs
            - mountPath: /usr/share/elasticsearch/data
              name: esdata01
      restartPolicy: Always
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs
        - name: esdata01
          persistentVolumeClaim:
            claimName: esdata01
