apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: esdata01
  name: esdata01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard