apiVersion: v1
kind: Service
metadata:
  annotations:
    co.elastic.logs/module: kibana
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  type: NodePort
  ports:
    - name: "5601"
      port: 5601
      targetPort: 5601
      nodePort: 30561
  selector:
    io.kompose.service: kibana
