apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: model-data
  name: model-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard